
// This file is auto-generated. Do not edit manually.
export const migrationData: { [key: string]: string } = {
  "meta/_journal.json": "{\n  \"version\": \"7\",\n  \"dialect\": \"sqlite\",\n  \"entries\": [\n    {\n      \"idx\": 0,\n      \"version\": \"6\",\n      \"when\": 1751933028499,\n      \"tag\": \"0000_needy_sersi\",\n      \"breakpoints\": true\n    },\n    {\n      \"idx\": 1,\n      \"version\": \"6\",\n      \"when\": 1753848150397,\n      \"tag\": \"0001_foamy_glorian\",\n      \"breakpoints\": true\n    },\n    {\n      \"idx\": 2,\n      \"version\": \"6\",\n      \"when\": 1753904120281,\n      \"tag\": \"0002_far_whirlwind\",\n      \"breakpoints\": true\n    },\n    {\n      \"idx\": 3,\n      \"version\": \"6\",\n      \"when\": 1766740353224,\n      \"tag\": \"0003_last_carlie_cooper\",\n      \"breakpoints\": true\n    },\n    {\n      \"idx\": 4,\n      \"version\": \"6\",\n      \"when\": 1771694749783,\n      \"tag\": \"0004_hot_namor\",\n      \"breakpoints\": true\n    },\n    {\n      \"idx\": 5,\n      \"version\": \"6\",\n      \"when\": 1771782192498,\n      \"tag\": \"0005_flowery_marten_broadcloak\",\n      \"breakpoints\": true\n    },\n    {\n      \"idx\": 6,\n      \"version\": \"6\",\n      \"when\": 1772039909079,\n      \"tag\": \"0006_nebulous_wendell_rand\",\n      \"breakpoints\": true\n    },\n    {\n      \"idx\": 7,\n      \"version\": \"6\",\n      \"when\": 1783301918841,\n      \"tag\": \"0007_giant_shadow_king\",\n      \"breakpoints\": true\n    },\n    {\n      \"idx\": 8,\n      \"version\": \"6\",\n      \"when\": 1784080934338,\n      \"tag\": \"0008_futuristic_harry_osborn\",\n      \"breakpoints\": true\n    },\n    {\n      \"idx\": 9,\n      \"version\": \"6\",\n      \"when\": 1784168550264,\n      \"tag\": \"0009_large_liz_osborn\",\n      \"breakpoints\": true\n    },\n    {\n      \"idx\": 10,\n      \"version\": \"6\",\n      \"when\": 1784354247147,\n      \"tag\": \"0010_condemned_human_robot\",\n      \"breakpoints\": true\n    }\n  ]\n}",
  "meta/0000_snapshot.json": "{\n  \"version\": \"6\",\n  \"dialect\": \"sqlite\",\n  \"id\": \"bf0d3f75-6d97-4a9d-b105-8052c6303306\",\n  \"prevId\": \"00000000-0000-0000-0000-000000000000\",\n  \"tables\": {\n    \"accounts\": {\n      \"name\": \"accounts\",\n      \"columns\": {\n        \"account\": {\n          \"name\": \"account\",\n          \"type\": \"text\",\n          \"primaryKey\": true,\n          \"notNull\": true,\n          \"autoincrement\": false\n        },\n        \"min_ms\": {\n          \"name\": \"min_ms\",\n          \"type\": \"integer\",\n          \"primaryKey\": false,\n          \"notNull\": true,\n          \"autoincrement\": false\n        },\n        \"min_kb\": {\n          \"name\": \"min_kb\",\n          \"type\": \"integer\",\n          \"primaryKey\": false,\n          \"notNull\": true,\n          \"autoincrement\": false\n        },\n        \"inc_ms\": {\n          \"name\": \"inc_ms\",\n          \"type\": \"integer\",\n          \"primaryKey\": false,\n          \"notNull\": true,\n          \"autoincrement\": false\n        },\n        \"inc_kb\": {\n          \"name\": \"inc_kb\",\n          \"type\": \"integer\",\n          \"primaryKey\": false,\n          \"notNull\": true,\n          \"autoincrement\": false\n        },\n        \"max_fee\": {\n          \"name\": \"max_fee\",\n          \"type\": \"text\",\n          \"primaryKey\": false,\n          \"notNull\": true,\n          \"autoincrement\": false\n        }\n      },\n      \"indexes\": {},\n      \"foreignKeys\": {},\n      \"compositePrimaryKeys\": {},\n      \"uniqueConstraints\": {},\n      \"checkConstraints\": {}\n    }\n  },\n  \"views\": {},\n  \"enums\": {},\n  \"_meta\": {\n    \"schemas\": {},\n    \"tables\": {},\n    \"columns\": {}\n  },\n  \"internal\": {\n    \"indexes\": {}\n  }\n}",
  "0000_needy_sersi.sql": "CREATE TABLE `accounts` (\n\t`account` text PRIMARY KEY NOT NULL,\n\t`min_ms` integer NOT NULL,\n\t`min_kb` integer NOT NULL,\n\t`inc_ms` integer NOT NULL,\n\t`inc_kb` integer NOT NULL,\n\t`max_fee` text NOT NULL\n);\n",
  "0001_foamy_glorian.sql": "CREATE TABLE `contracts` (\n\t`contract` text PRIMARY KEY NOT NULL,\n\t`abi` text NOT NULL\n);\n",
  "0002_far_whirlwind.sql": "CREATE TABLE `manager` (\n\t`account` text PRIMARY KEY NOT NULL,\n\t`permission` text NOT NULL,\n\t`key` text NOT NULL\n);\n",
  "0003_last_carlie_cooper.sql": "CREATE TABLE `usage` (\n\t`account` text PRIMARY KEY NOT NULL,\n\t`cpu` integer DEFAULT 0 NOT NULL,\n\t`net` integer DEFAULT 0 NOT NULL\n);\n",
  "0004_hot_namor.sql": "DROP TABLE `contracts`;",
  "0005_flowery_marten_broadcloak.sql": "CREATE TABLE `provider` (\n\t`account` text PRIMARY KEY NOT NULL,\n\t`permission` text NOT NULL,\n\t`key` text NOT NULL\n);\n",
  "0006_nebulous_wendell_rand.sql": "DROP TABLE `usage`;--> statement-breakpoint\nCREATE TABLE `usage` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`account` text NOT NULL,\n\t`cpu` integer NOT NULL,\n\t`net` integer NOT NULL,\n\t`created_at` integer NOT NULL\n);--> statement-breakpoint\nCREATE INDEX `idx_usage_account_created` ON `usage` (`account`,`created_at`);",
  "0007_giant_shadow_king.sql": "CREATE TABLE `config` (\n\t`scope` text DEFAULT 'global' NOT NULL,\n\t`key` text NOT NULL,\n\t`value` text NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tPRIMARY KEY(`scope`, `key`)\n);\n",
  "0008_futuristic_harry_osborn.sql": "CREATE TABLE `provider_bucket` (\n\t`name` text PRIMARY KEY NOT NULL,\n\t`priority` integer NOT NULL,\n\t`limit_ms` integer NOT NULL,\n\t`limit_kb` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `provider_rule` (\n\t`name` text PRIMARY KEY NOT NULL,\n\t`bucket` text NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `provider_rule_pattern` (\n\t`rule` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`pattern` text NOT NULL,\n\tPRIMARY KEY(`rule`, `kind`, `pattern`)\n);\n--> statement-breakpoint\nALTER TABLE `usage` ADD `bucket` text DEFAULT 'wildcard' NOT NULL;--> statement-breakpoint\nCREATE INDEX `idx_usage_account_bucket_created` ON `usage` (`account`,`bucket`,`created_at`);",
  "0009_large_liz_osborn.sql": "CREATE TABLE `tokens` (\n\t`name` text PRIMARY KEY NOT NULL,\n\t`hash` text NOT NULL,\n\t`level` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`last_used_at` integer\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `tokens_hash_unique` ON `tokens` (`hash`);",
  "0010_condemned_human_robot.sql": "CREATE TABLE `provider_bucket_account` (\n\t`bucket` text NOT NULL,\n\t`account` text NOT NULL,\n\tPRIMARY KEY(`bucket`, `account`)\n);\n--> statement-breakpoint\nCREATE INDEX `idx_bucket_account_account` ON `provider_bucket_account` (`account`);"
};
